# Generated by Django 4.0.1 on 2022-01-08 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0009_restriction_training_restrictions'),
        ('members', '0006_auto_20210424_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(verbose_name='Start of validity')),
                ('date_end', models.DateField(verbose_name='End of validity')),
                ('restrictions_fulfilled', models.ManyToManyField(blank=True, related_name='valid_certs', to='trainings.Restriction', verbose_name='Restrictions fulfilled')),
                ('restrictions_part_fulfilled', models.ManyToManyField(blank=True, related_name='part_valid_certs', to='trainings.Restriction', verbose_name='Restrictions partially fulfilled')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['-date_end', 'date_start'],
            },
        ),
    ]
