# Generated by Django 3.0.5 on 2020-05-02 11:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('start', models.DateTimeField(verbose_name='Start')),
                ('duration', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(240)], verbose_name='Dauer (min)')),
                ('instructor', models.ManyToManyField(blank=True, default=None, related_name='further_instructors', to=settings.AUTH_USER_MODEL)),
                ('main_instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='main_instructor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
