# Generated by Django 3.0.5 on 2020-05-12 21:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainings', '0002_auto_20200507_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='participants',
            field=models.ManyToManyField(blank=True, default=None, related_name='trainings', to=settings.AUTH_USER_MODEL, verbose_name='Teilnehmer'),
        ),
        migrations.AlterField(
            model_name='training',
            name='registered_participants',
            field=models.ManyToManyField(blank=True, default=None, related_name='trainings_registered', to=settings.AUTH_USER_MODEL, verbose_name='Angemeldete Teilnehmer'),
        ),
    ]
