# Generated by Django 3.0.5 on 2020-05-02 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0002_auto_20200502_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=150, verbose_name='Strasse')),
                ('house_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Hausnummer')),
                ('area_code', models.CharField(blank=True, max_length=15, null=True, verbose_name='Potsleitzahl')),
                ('city', models.CharField(max_length=180, verbose_name='Stadt')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Land')),
            ],
        ),
        migrations.CreateModel(
            name='TargetGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(max_length=500, verbose_name='Beschreibung')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('capacity', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Kapazität (Anzahl Personen)')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainings.Address')),
            ],
        ),
        migrations.AddField(
            model_name='training',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainings.Location'),
        ),
        migrations.AddField(
            model_name='training',
            name='target_group',
            field=models.ManyToManyField(to='trainings.TargetGroup', verbose_name='Zielgruppe'),
        ),
    ]
