# Generated by Django 3.0.5 on 2020-05-23 14:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainings', '0003_auto_20200512_2353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='targetgroup',
            options={'verbose_name': 'Target Group', 'verbose_name_plural': 'Target Groups'},
        ),
        migrations.AlterModelOptions(
            name='training',
            options={'verbose_name': 'Training', 'verbose_name_plural': 'Trainings'},
        ),
        migrations.AlterField(
            model_name='address',
            name='area_code',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=180, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='address',
            name='house_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='House number'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=150, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='location',
            name='capacity',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Capacity (number of people)'),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='targetgroup',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='training',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
        migrations.AlterField(
            model_name='training',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=15, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Capacity (number of people)'),
        ),
        migrations.AlterField(
            model_name='training',
            name='coordinator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coordinated_trainings', to=settings.AUTH_USER_MODEL, verbose_name='Coordinator'),
        ),
        migrations.AlterField(
            model_name='training',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='training',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='training',
            name='duration',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(240)], verbose_name='Duration (min.)'),
        ),
        migrations.AlterField(
            model_name='training',
            name='instructor',
            field=models.ManyToManyField(blank=True, default=None, related_name='assistant', to=settings.AUTH_USER_MODEL, verbose_name='Instructor'),
        ),
        migrations.AlterField(
            model_name='training',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainings', to='trainings.Location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='training',
            name='main_instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instructor', to=settings.AUTH_USER_MODEL, verbose_name='Main Instructor'),
        ),
        migrations.AlterField(
            model_name='training',
            name='participants',
            field=models.ManyToManyField(blank=True, default=None, related_name='trainings', to=settings.AUTH_USER_MODEL, verbose_name='Participants'),
        ),
        migrations.AlterField(
            model_name='training',
            name='registered_participants',
            field=models.ManyToManyField(blank=True, default=None, related_name='trainings_registered', to=settings.AUTH_USER_MODEL, verbose_name='Registered Participants'),
        ),
        migrations.AlterField(
            model_name='training',
            name='registration_close',
            field=models.DateTimeField(verbose_name='Registration closing'),
        ),
        migrations.AlterField(
            model_name='training',
            name='registration_open',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registration opening'),
        ),
        migrations.AlterField(
            model_name='training',
            name='target_group',
            field=models.ManyToManyField(to='trainings.TargetGroup', verbose_name='Target Group'),
        ),
        migrations.AlterField(
            model_name='training',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
