# Generated by Django 3.0.7 on 2020-06-21 15:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainings', '0005_auto_20200528_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='instructor',
            new_name='instructors',
        ),
        migrations.AddField(
            model_name='training',
            name='visitors',
            field=models.ManyToManyField(blank=True, default=None, related_name='visited_trainings', to=settings.AUTH_USER_MODEL, verbose_name='Visitors'),
        ),
    ]
