# Generated by Django 3.0.5 on 2020-05-03 19:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainings', '0005_auto_20200502_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archiviert'),
        ),
        migrations.AddField(
            model_name='training',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Gelöscht'),
        ),
        migrations.AddField(
            model_name='training',
            name='participants',
            field=models.ManyToManyField(blank=True, default=None, related_name='trainings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='training',
            name='registered_participants',
            field=models.ManyToManyField(blank=True, default=None, related_name='trainings_registered', to=settings.AUTH_USER_MODEL),
        ),
    ]
