# Generated by Django 3.1.2 on 2020-10-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0006_auto_20200621_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='enable_coordinator',
            field=models.BooleanField(default=True, verbose_name='Use coordinator'),
        ),
        migrations.AddField(
            model_name='training',
            name='enable_registration',
            field=models.BooleanField(default=True, verbose_name='Allow registration'),
        ),
        migrations.AddField(
            model_name='training',
            name='enable_visitors',
            field=models.BooleanField(default=True, verbose_name='Allow visitors'),
        ),
    ]
