# Generated by Django 4.0.1 on 2022-01-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0008_auto_20210424_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restriction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='Name')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Restriction',
                'verbose_name_plural': 'Restrictions',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='training',
            name='restrictions',
            field=models.ManyToManyField(blank=True, to='trainings.Restriction', verbose_name='Restriction'),
        ),
    ]
