name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2.1.4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      env:
        PYTHON_DJANGO_SECRET_KEY: M1iNLFveaBcsXvbGFKOo
        PYTHON_DJANGO_DB_ENGINE: django.db.backends.sqlite3
        PYTHON_DJANGO_DB_NAME: os.path.join(BASE_DIR, 'db.sqlite3')
        PYTHON_DJANGO_DB_USER: ''
        PYTHON_DJANGO_DB_HOST: ''
        PYTHON_DJANGO_EMAIL_BACKEND: django.core.mail.backends.locmem.EmailBackend
        PYTHON_DJANGO_EMAIL_HOST: ''
        PYTHON_DJANGO_EMAIL_PORT: ''
        PYTHON_DJANGO_EMAIL_USE_SSL: True
        PYTHON_DJANGO_EMAIL_USER: user@localhost
        PYTHON_DJANGO_EMAIL_FROM: no-reply@localhost
        PYTHON_DJANGO_EMAIL_PASSWORD: ''
        PYTHON_DJANGO_STATIC_ROOT: ''
      run: |
        cd training_planner
        python manage.py test
